<a href="https://colab.research.google.com/github/ganeshagrahari/Pytorch-Framework/blob/main/14_LSTM_using_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install nltk

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize
import nltk

In [3]:
document = """About the Program
What is the course fee for  Data Science Mentorship Program (DSMP 2023)
The course follows a monthly subscription model where you have to make monthly payments of Rs 799/month.
What is the total duration of the course?
The total duration of the course is 7 months. So the total course fee becomes 799*7 = Rs 5600(approx.)
What is the syllabus of the mentorship program?
We will be covering the following modules:
Python Fundamentals
Python libraries for Data Science
Data Analysis
SQL for Data Science
Maths for Machine Learning
ML Algorithms
Practical ML
MLOPs
Case studies
You can check the detailed syllabus here - https://learnwith.campusx.in/courses/CampusX-Data-Science-Mentorship-Program-637339afe4b0615a1bbed390
Will Deep Learning and NLP be a part of this program?
No, NLP and Deep Learning both are not a part of this program’s curriculum.
What if I miss a live session? Will I get a recording of the session?
Yes all our sessions are recorded, so even if you miss a session you can go back and watch the recording.
Where can I find the class schedule?
Checkout this google sheet to see month by month time table of the course - https://docs.google.com/spreadsheets/d/16OoTax_A6ORAeCg4emgexhqqPv3noQPYKU7RJ6ArOzk/edit?usp=sharing.
What is the time duration of all the live sessions?
Roughly, all the sessions last 2 hours.
What is the language spoken by the instructor during the sessions?
Hinglish
How will I be informed about the upcoming class?
You will get a mail from our side before every paid session once you become a paid user.
Can I do this course if I am from a non-tech background?
Yes, absolutely.
I am late, can I join the program in the middle?
Absolutely, you can join the program anytime.
If I join/pay in the middle, will I be able to see all the past lectures?
Yes, once you make the payment you will be able to see all the past content in your dashboard.
Where do I have to submit the task?
You don’t have to submit the task. We will provide you with the solutions, you have to self evaluate the task yourself.
Will we do case studies in the program?
Yes.
Where can we contact you?
You can mail us at nitish.campusx@gmail.com
Payment/Registration related questions
Where do we have to make our payments? Your YouTube channel or website?
You have to make all your monthly payments on our website. Here is the link for our website - https://learnwith.campusx.in/
Can we pay the entire amount of Rs 5600 all at once?
Unfortunately no, the program follows a monthly subscription model.
What is the validity of monthly subscription? Suppose if I pay on 15th Jan, then do I have to pay again on 1st Feb or 15th Feb
15th Feb. The validity period is 30 days from the day you make the payment. So essentially you can join anytime you don’t have to wait for a month to end.
What if I don’t like the course after making the payment. What is the refund policy?
You get a 7 days refund period from the day you have made the payment.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmail.com
Post registration queries
Till when can I view the paid videos on the website?
This one is tricky, so read carefully. You can watch the videos till your subscription is valid. Suppose you have purchased subscription on 21st Jan, you will be able to watch all the past paid sessions in the period of 21st Jan to 20th Feb. But after 21st Feb you will have to purchase the subscription again.
But once the course is over and you have paid us Rs 5600(or 7 installments of Rs 799) you will be able to watch the paid sessions till Aug 2024.
Why lifetime validity is not provided?
Because of the low course fee.
Where can I reach out in case of a doubt after the session?
You will have to fill a google form provided in your dashboard and our team will contact you for a 1 on 1 doubt clearance session
If I join the program late, can I still ask past week doubts?
Yes, just select past week doubt in the doubt clearance google form.
I am living outside India and I am not able to make the payment on the website, what should I do?
You have to contact us by sending a mail at nitish.campusx@gmai.com
Certificate and Placement Assistance related queries
What is the criteria to get the certificate?
There are 2 criterias:
You have to pay the entire fee of Rs 5600
You have to attempt all the course assessments.
I am joining late. How can I pay payment of the earlier months?
You will get a link to pay fee of earlier months in your dashboard once you pay for the current month.
I have read that Placement assistance is a part of this program. What comes under Placement assistance?
This is to clarify that Placement assistance does not mean Placement guarantee. So we dont guarantee you any jobs or for that matter even interview calls. So if you are planning to join this course just for placements, I am afraid you will be disappointed. Here is what comes under placement assistance
Portfolio Building sessions
Soft skill sessions
Sessions with industry mentors
Discussion on Job hunting strategies
"""


In [4]:
# Tokenization
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [5]:
#tokenize
tokens = word_tokenize(document.lower())

In [6]:
#build vocab
vocab = {'<unk>' : 0}

for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token] = len(vocab)

len(vocab)

289

In [7]:
#extract sentences from data
input_sentences = document.split('\n')

In [8]:
def text_to_indices(sentence,vocab):
  numerical_sentence = []
  for token in sentence:
    if token in vocab:
      numerical_sentence.append(vocab[token])
    else:
      numerical_sentence.append(vocab['<unk>'])

  return numerical_sentence



In [9]:
input_numrical_sentences = []
for sentence in input_sentences:
  input_numrical_sentences.append(text_to_indices(word_tokenize(sentence.lower()),vocab))


In [10]:
len(input_numrical_sentences)

78

In [11]:
training_sequences = []
for sentence in input_numrical_sentences:
  for i in range(1,len(sentence)):
    training_sequences.append(sentence[:i+1])


In [12]:
len(training_sequences)

942

In [13]:
training_sequences[:5]

[[1, 2], [1, 2, 3], [4, 5], [4, 5, 2], [4, 5, 2, 6]]

In [14]:
len_list = []
for sequence in training_sequences:
  len_list.append(len(sequence))

max(len_list)


62

In [15]:
training_sequences[0]

[1, 2]

In [16]:
padded_tarining_sequences = []
for sequence in training_sequences:
  padded_tarining_sequences.append([0]*(max(len_list)-len(sequence))+sequence)


In [17]:
len(padded_tarining_sequences[0])

62

In [18]:
padded_tarining_sequences = torch.tensor(padded_tarining_sequences,dtype = torch.long)

In [19]:
padded_tarining_sequences.shape

torch.Size([942, 62])

In [20]:
x = padded_tarining_sequences[:,:-1]
y = padded_tarining_sequences[:,-1]

In [21]:
x

tensor([[  0,   0,   0,  ...,   0,   0,   1],
        [  0,   0,   0,  ...,   0,   1,   2],
        [  0,   0,   0,  ...,   0,   0,   4],
        ...,
        [  0,   0,   0,  ...,   0, 285, 176],
        [  0,   0,   0,  ..., 285, 176, 286],
        [  0,   0,   0,  ..., 176, 286, 287]])

In [22]:
y

tensor([  2,   3,   5,   2,   6,   7,   8,   9,  10,  11,   3,  12,  13,  14,
         15,   6,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  18,  26,
         27,  28,  29,  30,   5,   2,  31,  32,  27,   2,   6,  33,  31,  32,
         27,   2,   6,   5,  34,  35,  30,  36,   2,  31,   6,   7,  37,  38,
         39,  34,  40,  28,  41,  12,  42,  30,  15,   5,   2,  43,  27,   2,
         11,   3,  33,  45,  46,  47,   2,  48,  49,  50,  52,  53,   8,   9,
         10,  54,   8,   9,  10,   8,  57,  58,  60,  59,  64,  65,  66,   2,
         67,  43,  68,  69,  70,  50,  71,  72,  58,  73,  74,  46,  17,  75,
         27,  76,   3,  33,  78,  74,  73,  72,  58,  79,  80,  81,  17,  75,
         27,  76,   3,  82,  83,  84,  30,  85,  86,  87,  17,  88,  89,  33,
         45,  86,  90,  17,  91,  27,   2,  89,  33,  93,  94,  95,  80,  96,
         78,  36,  97,  85,  22,  87,  17,  89,  22,  65,  98,  99,  73, 100,
          2,  91,  30,  65,  86, 101,   2, 102, 103,  33,  76, 1

In [23]:
class CustomDataset(Dataset):

  def __init__(self,x,y):
    self.x = x
    self.y = y


  def __len__(self):
    return self.x.shape[0]

  def __getitem__(self,index):
    return self.x[index],self.y[index]

In [24]:
dataset = CustomDataset(x,y)

In [25]:
dataset[0]

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]),
 tensor(2))

In [26]:
dataloader = DataLoader(dataset,batch_size=32,shuffle=True)

In [27]:
for input, output in dataloader:
  print(input,output)

tensor([[  0,   0,   0,  ...,  23,  24, 153],
        [  0,   0,   0,  ...,   0,  22,  23],
        [  0,   0,   0,  ...,   2,  31,  32],
        ...,
        [  0,   0,   0,  ...,   0,   0,  92],
        [  0,   0,   0,  ...,  76,   6,  85],
        [  0,   0,   0,  ...,  12,  42,  30]]) tensor([  2,  24,  27, 158,  34, 251, 168, 135, 177,  22, 152, 190, 115,  95,
        110,  39, 223, 263, 211,  19,   2,  32,   5,  97,  83,  23, 270,  30,
         85,  78,  86,  15])
tensor([[  0,   0,   0,  ..., 245, 147, 246],
        [  0,   0,   0,  ...,   6, 200, 201],
        [  0,   0,   0,  ..., 132,  22, 133],
        ...,
        [  0,   0,   0,  ...,  17, 108,  24],
        [  0,   0,   0,  ..., 142, 151, 152],
        [  0,   0,   0,  ...,   2, 180, 181]]) tensor([247,   2,  17, 128, 195,  30,  95,  74,   2,  30,   8,  46, 238,  69,
        224,  10, 227,  30,   2,  27,  23,  27,  78,  22, 195,  38, 126,  65,
         13, 198, 132,  27])
tensor([[  0,   0,   0,  ...,   0,  21,  65],
    

In [28]:
  class LSTMModel(nn.Module):
    def __init__(self,vocab_size):
      super().__init__()
      self.embedding = nn.Embedding(vocab_size,100)
      self.lstm = nn.LSTM(100,150,batch_first=True)
      self.fc = nn.Linear(150,vocab_size)

    def forward(self,x):
      embedded = self.embedding(x)
      intermediate_hidden_state,(final_hidden_state,final_cell_state)=self.lstm(embedded)
      output = self.fc(final_hidden_state.squeeze(0))

      return output

In [29]:
x = nn.Embedding(289,100)
y = nn.LSTM(100,150,batch_first=True)


In [30]:
a = dataset[0][0].unsqueeze(0)

In [31]:
b = x(a)

In [32]:
c ,d =y(b)

In [33]:
c.shape #set of all intermediate hidden states

torch.Size([1, 61, 150])

In [34]:
e, f = d

In [35]:
e.shape

torch.Size([1, 1, 150])

In [36]:
f.shape

torch.Size([1, 1, 150])

In [37]:
z = nn.Linear(150,289)

In [38]:
z(f.squeeze(0)).shape

torch.Size([1, 289])

In [39]:
model = LSTMModel(len(vocab))

In [40]:
device= torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [41]:
model.to(device)

LSTMModel(
  (embedding): Embedding(289, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=289, bias=True)
)

In [42]:
epochs = 50
learning_rate = 0.001
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)

In [43]:
#training loop
for epoch in range(epochs):
  total_loss = 0
  for batch_x,batch_y in dataloader:
    batch_x,batch_y =batch_x.to(device), batch_y.to(device)

    optimizer.zero_grad()

    output = model(batch_x)

    loss = criterion(output, batch_y)

    loss.backward()

    optimizer.step()

    total_loss+=loss.item()
  print(f"Epoch: {epoch+1},loss:{total_loss:.4f}")

Epoch: 1,loss:165.7983
Epoch: 2,loss:147.9159
Epoch: 3,loss:136.0380
Epoch: 4,loss:123.3238
Epoch: 5,loss:110.8066
Epoch: 6,loss:99.2913
Epoch: 7,loss:88.9425
Epoch: 8,loss:79.3817
Epoch: 9,loss:70.2991
Epoch: 10,loss:62.2151
Epoch: 11,loss:55.5910
Epoch: 12,loss:48.8310
Epoch: 13,loss:43.0809
Epoch: 14,loss:37.7605
Epoch: 15,loss:33.3995
Epoch: 16,loss:29.3730
Epoch: 17,loss:26.2130
Epoch: 18,loss:23.0582
Epoch: 19,loss:20.3071
Epoch: 20,loss:18.0002
Epoch: 21,loss:16.3312
Epoch: 22,loss:14.8036
Epoch: 23,loss:13.4919
Epoch: 24,loss:12.2376
Epoch: 25,loss:11.3930
Epoch: 26,loss:10.6338
Epoch: 27,loss:9.7597
Epoch: 28,loss:9.0905
Epoch: 29,loss:8.7391
Epoch: 30,loss:8.3564
Epoch: 31,loss:7.7131
Epoch: 32,loss:7.3258
Epoch: 33,loss:6.9803
Epoch: 34,loss:6.7634
Epoch: 35,loss:6.4294
Epoch: 36,loss:6.2415
Epoch: 37,loss:5.9654
Epoch: 38,loss:5.6792
Epoch: 39,loss:5.5754
Epoch: 40,loss:5.5341
Epoch: 41,loss:5.2709
Epoch: 42,loss:5.1591
Epoch: 43,loss:5.1088
Epoch: 44,loss:4.9020
Epoch: 45,

In [49]:
#prediction
def prediction(model,vocab,text):
  #tokenize
  tokenized_text = word_tokenize(text.lower())

  #text -> numerical indices
  numerical_text = text_to_indices(tokenized_text,vocab)

  #padding
  padded_text = torch.tensor([0]*(61-len(numerical_text))+ numerical_text,dtype = torch.long).unsqueeze(0)

  #send to model
  output = model(padded_text)

  #predicted index
  value, index = torch.max(output,dim = 1)
  #merge with text
  return text + " "+list(vocab.keys())[index]

In [51]:
prediction(model,vocab,"the course after making")

'the course after making the'

In [54]:
import time
num_token = 10
input_text = "the course after making"
for i in range(num_token):
  output_text = prediction(model,vocab,input_text)
  print(output_text)
  input_text = output_text
  time.sleep(0.5)

the course after making the
the course after making the payment
the course after making the payment .
the course after making the payment . what
the course after making the payment . what is
the course after making the payment . what is the
the course after making the payment . what is the refund
the course after making the payment . what is the refund policy
the course after making the payment . what is the refund policy ?
the course after making the payment . what is the refund policy ? ?
