<a href="https://colab.research.google.com/github/ganeshagrahari/Pytorch-Framework/blob/main/Training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Plan of attack:-**
## 1. We will build a simple neural network
## 2. Train it on world dataset
## 3. Will mimic the Pytorch workflow
## 4. End result is not important


# Code flow:-
## 1. Load the dataset
## 2. Basic preprocessing
## 3. Training process :- a) Creating the model.  b) Forward pass  c)Loss calculation  d)Backprop e)Parameters update
## 4. Model evaluation

In [30]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [31]:
df =pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [32]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [33]:
df.shape

(569, 33)

In [34]:
df.drop(columns={'id','Unnamed: 32'},inplace=True)

In [35]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## Train Test Split

In [36]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

## Scaling

In [37]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [38]:
X_train

array([[-0.22275411,  0.32893652, -0.1847231 , ...,  1.65453609,
        -0.13834215,  1.35395345],
       [ 1.64743723,  2.0320582 ,  1.55911682, ...,  0.71144949,
        -0.52253606, -0.97353003],
       [ 1.17778015, -0.19827477,  1.14760319, ...,  0.73240697,
         1.31342039,  0.13621043],
       ...,
       [ 0.57031951, -0.84468165,  0.47940285, ...,  0.30577256,
        -0.96722008, -0.63466489],
       [-0.726159  ,  1.15872124, -0.6748725 , ...,  0.23242138,
        -0.14488162,  0.93108633],
       [ 0.5843811 ,  0.8951156 ,  0.65460172, ...,  1.63956646,
         3.15918604,  0.72765296]])

In [39]:
y_train

39     M
565    M
85     M
235    B
510    B
      ..
138    M
299    B
508    B
537    B
370    M
Name: diagnosis, Length: 455, dtype: object

## Label encoder

In [40]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [41]:
y_train

array([1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,

In [42]:
y_test

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0])

## Numpy array to Pytorch tensors

In [43]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [44]:
X_train_tensor.shape

torch.Size([455, 30])

In [45]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

In [46]:
class MysimpleNN():
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1, dtype =torch.float64, requires_grad=True)
    self.bias = torch.zeros(1,dtype= torch.float64,requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

## Important parameters

In [47]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

In [48]:
# Create model
model = MysimpleNN(X_train_tensor)
## defining a loop:---
for epoch in range(epochs):
    #1.Forward pass:-
    y_pred = model.forward(X_train_tensor)
    #2.Loss calculate:-
    loss =model.loss_function(y_pred,y_train_tensor)
    #3.backward pass
    loss.backward()

    #3.parameters update
    with torch.no_grad():# we have to run this fxn with gradient tracking
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
    #zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()
    # print loss in each epoch
    print(f'Epoch:{epoch+1} Loss:{loss.item()}')







Epoch:1 Loss:4.219041974503242
Epoch:2 Loss:4.124879398949257
Epoch:3 Loss:4.026319219156912
Epoch:4 Loss:3.9186719099838463
Epoch:5 Loss:3.806518007512375
Epoch:6 Loss:3.689326352650752
Epoch:7 Loss:3.5701650650118784
Epoch:8 Loss:3.4467326119877733
Epoch:9 Loss:3.315390858460215
Epoch:10 Loss:3.177569164008847
Epoch:11 Loss:3.03772184929456
Epoch:12 Loss:2.895492058891607
Epoch:13 Loss:2.7488821305191413
Epoch:14 Loss:2.597321759898667
Epoch:15 Loss:2.442006609849522
Epoch:16 Loss:2.2842389324331895
Epoch:17 Loss:2.1303176378554753
Epoch:18 Loss:1.9761844186142414
Epoch:19 Loss:1.818671851146166
Epoch:20 Loss:1.6677284295466557
Epoch:21 Loss:1.5262289131024742
Epoch:22 Loss:1.3914538867809443
Epoch:23 Loss:1.2712562187091645
Epoch:24 Loss:1.1668629919267115
Epoch:25 Loss:1.0788422221971246


In [50]:
model.weights

tensor([[ 0.3767],
        [ 0.2871],
        [ 0.2029],
        [ 0.2296],
        [ 0.2521],
        [-0.4150],
        [-0.3255],
        [ 0.2897],
        [-0.1672],
        [ 0.1269],
        [ 0.1323],
        [-0.0448],
        [ 0.2216],
        [ 0.1809],
        [ 0.4027],
        [ 0.1172],
        [ 0.2985],
        [ 0.1450],
        [ 0.6152],
        [ 0.3624],
        [-0.4452],
        [-0.1830],
        [-0.0650],
        [-0.1503],
        [ 0.1171],
        [ 0.0152],
        [ 0.0321],
        [-0.2667],
        [ 0.5366],
        [ 0.4250]], dtype=torch.float64, requires_grad=True)

In [52]:
model.bias

tensor([-0.0496], dtype=torch.float64, requires_grad=True)

# Evaluation

In [60]:
# model evaluation
with torch.no_grad():
  y_pred= model.forward(X_test_tensor)
  y_pred = (y_pred > 0.9).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy:{accuracy.item()}')



Accuracy:0.6388119459152222
