<a href="https://colab.research.google.com/github/ganeshagrahari/Pytorch-Framework/blob/main/NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Plan of action

## 1. Revison
## 2. Improvemnets
## 3. The nn Module
## 4. The torch.optim module


## Improvements:-
### 1. Building the neural network using nn module.
### 2. Using built-in activation function
### 3. Using built-in loss function.
###4 . Using built-in optimizer


In [50]:
# Creating model class
import torch
import torch.nn as nn

class Model(nn.Module):     # your class should inherit nn.Module that you can use properties of nn Modules!
        def __init__(self,num_features):
          super().__init__()
          self.linear = nn.Linear(num_features,1)
          self.sigmoid = nn.Sigmoid()

        def forward(self,features):
          out = self.linear(features) #z=wx+b z = out
          out = self.sigmoid(out) # we got y_pred from here

          return out




In [51]:
# Creating a dataset
features = torch.rand(10,5)

#Creating a model
model = Model(features.shape[1])

#call the  forward pass
model(features)

tensor([[0.5113],
        [0.5462],
        [0.4399],
        [0.4351],
        [0.4976],
        [0.4747],
        [0.4868],
        [0.5041],
        [0.5783],
        [0.5821]], grad_fn=<SigmoidBackward0>)

In [52]:
# show model weights and bias
#model.linear.weight
model.linear.bias

Parameter containing:
tensor([0.1618], requires_grad=True)

In [53]:
!pip install torchinfo

In [54]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [55]:
#  craeting nn with a hidden layer
# Creating model class
import torch
import torch.nn as nn

class Model(nn.Module):     # your class should inherit nn.Module that you can use properties of nn Modules!
        def __init__(self,num_features):
          super().__init__()
          self.linear1 = nn.Linear(num_features,3)# this is for hidden layer
          self.relu = nn.ReLU()

          self.linear2 = nn.Linear(3,1)# this is for futher layer
          self.sigmoid = nn.Sigmoid()

        def forward(self,features):
          out = self.linear1(features) #z=wx+b z = out
          out = self.relu(out)
          out = self.linear2(out)
          out = self.sigmoid(out) # we got y_pred from here

          return out




In [56]:
# Creating a dataset
features = torch.rand(10,5)

#Creating a model
model = Model(features.shape[1])

#call the  forward pass
model(features)

tensor([[0.5637],
        [0.5708],
        [0.5500],
        [0.5879],
        [0.5635],
        [0.5543],
        [0.5944],
        [0.5816],
        [0.5798],
        [0.5636]], grad_fn=<SigmoidBackward0>)

In [57]:
# show model weights and bias
#model.linear.weight
model.linear2.weight

Parameter containing:
tensor([[-0.4214,  0.3408, -0.0942]], requires_grad=True)

In [58]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [59]:
#sequential containers for forward pass fxn
import torch
import torch.nn as nn

class Model(nn.Module):     # your class should inherit nn.Module that you can use properties of nn Modules!
        def __init__(self,num_features):
          super().__init__()
          self.network  = nn.Sequential(
               nn.Linear(num_features,3),# this is for hidden layer
               nn.ReLU(),
               nn.Linear(3,1),# this is for futher layer
               nn.Sigmoid()
          )


        def forward(self,features):
          out = self.network(features)
          return out







In [60]:
# Creating a dataset
features = torch.rand(10,5)

#Creating a model
model = Model(features.shape[1])

#call the  forward pass
model(features)

tensor([[0.6194],
        [0.5970],
        [0.6227],
        [0.6173],
        [0.6111],
        [0.6340],
        [0.6157],
        [0.6214],
        [0.5833],
        [0.6084]], grad_fn=<SigmoidBackward0>)