<a href="https://colab.research.google.com/github/ganeshagrahari/Pytorch-Framework/blob/main/Dataset_%26_DataLoader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Rather than loading the entier data to the model we should load our data in the batches....

In [1]:
from sklearn.datasets import make_classification
import torch

In [3]:
#Step 1 : create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples = 10,   #number of samples
    n_features = 2,   #number of features
    n_informative =2,#number of informatives features
    n_redundant = 0,  #number of redundant features
    n_classes = 2,  #number of classes
    random_state = 42  #for reproducibility
)

In [5]:
X.shape

(10, 2)

In [6]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [7]:
y.shape

(10,)

In [8]:
# convert the data to pytorch tensor
X= torch.tensor(X , dtype=torch.float32)
y= torch.tensor(y , dtype=torch.float32)

In [9]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [10]:
y

tensor([1., 0., 0., 0., 0., 1., 1., 1., 1., 0.])

In [11]:
from torch.utils.data import Dataset, DataLoader

In [12]:
class CustomDataset(Dataset):
  def __init__(self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return self.features[index],self.labels[index]



In [13]:
dataset = CustomDataset(X,y)

In [14]:
len(dataset)

10

In [18]:
dataset[9]

(tensor([-0.5872, -1.9717]), tensor(0.))

In [19]:
dataloader = DataLoader(dataset,batch_size=2,shuffle=True)

In [20]:
for batch_features, batch_labels in dataloader:
  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[-0.7206, -0.9606],
        [-0.5872, -1.9717]])
tensor([0., 0.])
--------------------------------------------------
tensor([[-0.9382, -0.5430],
        [ 1.7273, -1.1858]])
tensor([1., 1.])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [ 1.8997,  0.8344]])
tensor([0., 1.])
--------------------------------------------------
tensor([[ 1.0683, -0.9701],
        [-1.9629, -0.9923]])
tensor([1., 0.])
--------------------------------------------------
tensor([[-1.1402, -0.8388],
        [ 1.7774,  1.5116]])
tensor([0., 1.])
--------------------------------------------------
