<a href="https://colab.research.google.com/github/ganeshagrahari/Pytorch-Framework/blob/main/pytorch_pipeline_using_dataset_and_dataloader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Now we are going to useing dataset and dataloader on training pipeline...

In [1]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df =pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [3]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns={'id','Unnamed: 32'},inplace=True)

In [6]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train

array([[-0.73130427, -0.26661433, -0.73122727, ..., -0.8822492 ,
        -1.07080657, -0.40310895],
       [-0.33757734,  0.47594123, -0.36035422, ..., -0.86832255,
        -0.62901663, -0.12081077],
       [ 0.06181472, -0.26430107, -0.00794277, ..., -0.57631697,
        -0.39549909, -0.38219797],
       ...,
       [-0.62366669, -0.14169844, -0.55317539, ...,  0.62409996,
         2.95737097,  3.10883442],
       [-0.28659112, -0.20646964, -0.36117474, ..., -0.95733203,
        -1.41950505, -1.21148325],
       [ 0.44421138,  0.01560305,  0.35226358, ..., -0.41918799,
        -0.32134149, -0.84829262]])

In [10]:
y_train

304    B
407    B
298    B
257    M
195    B
      ..
92     B
56     M
31     M
37     B
263    M
Name: diagnosis, Length: 455, dtype: object

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)


In [12]:
y_train

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,

In [13]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

In [16]:
torch.Size([455])

torch.Size([455])

## Defining our function

In [19]:
from torch.utils.data import Dataset, DataLoader


class Customdataset(Dataset):
  def __init__(self,features,labels):
    self.features = features
    self.labels = labels

  def __len__(self):
    return self.features.shape[0]

  def __getitem__(self,index):
    return  self.features[index],self.labels[index]

In [20]:
train_dataset = Customdataset (X_train_tensor,y_train_tensor)
test_dataset = Customdataset (X_test_tensor,y_test_tensor)

In [21]:
train_dataset[10]

(tensor([-0.2469, -0.2527, -0.2927, -0.3089, -1.5102, -0.8289, -0.4943, -0.5095,
         -1.2753, -1.0282, -0.7154, -0.9705, -0.7771, -0.4895, -0.3776, -0.5984,
         -0.5231, -0.5407, -1.1754, -0.7811, -0.2518, -0.2859, -0.3295, -0.3102,
         -0.1762, -0.3522, -0.3894, -0.1343, -1.0282, -0.7955]),
 tensor(0.))

In [22]:
train_loader = DataLoader(train_dataset,batch_size=32,shuffle=True)
test_loader = DataLoader(test_dataset,batch_size=32,shuffle=True)

## defining the model

In [23]:
import torch.nn as nn


class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):

    out = self.linear(features)
    out = self.sigmoid(out)

    return out

## Importanat Parameters

In [24]:
learning_rate = 0.1
epochs = 25

In [25]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

#define loss function
loss_function = nn.BCELoss()



## training pipeline

In [31]:

# define loop
for epoch in range(epochs):

  for batch_features, batch_labels in train_loader:

    # forward pass
    y_pred = model(batch_features)

    # loss calculate
    loss = loss_function(y_pred, batch_labels.view(-1,1))

    # clear gradients
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameters update
    optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.021693287417292595
Epoch: 2, Loss: 0.012612986378371716
Epoch: 3, Loss: 0.34155917167663574
Epoch: 4, Loss: 0.06334622204303741
Epoch: 5, Loss: 0.015496752224862576
Epoch: 6, Loss: 0.016168486326932907
Epoch: 7, Loss: 0.018070338293910027
Epoch: 8, Loss: 0.03915880247950554
Epoch: 9, Loss: 0.024273911491036415
Epoch: 10, Loss: 0.0992288812994957
Epoch: 11, Loss: 0.03172089904546738
Epoch: 12, Loss: 0.002337224781513214
Epoch: 13, Loss: 0.06700832396745682
Epoch: 14, Loss: 0.0008728231186978519
Epoch: 15, Loss: 0.0038452257867902517
Epoch: 16, Loss: 0.030081141740083694
Epoch: 17, Loss: 0.04429084062576294
Epoch: 18, Loss: 0.00430127652361989
Epoch: 19, Loss: 0.04975553974509239
Epoch: 20, Loss: 0.09386833757162094
Epoch: 21, Loss: 0.0002550051431171596
Epoch: 22, Loss: 0.008843972347676754
Epoch: 23, Loss: 0.003217016812413931
Epoch: 24, Loss: 0.03887850046157837
Epoch: 25, Loss: 0.005345748271793127


In [32]:
# model evaluation
model.eval() #set the model to evaluation mode
accuracy_list=[]

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    #forward pss
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.8).float() # convert probabilities to binary prediction


    #calculate accuracy for the curresnt batch
    batch_accuracy= (y_pred.view(-1)== batch_labels).float().mean().item()
    accuracy_list.append(batch_accuracy)

#calculate overall accuracy
overall_accuracy = sum(accuracy_list)/len(accuracy_list)
print(f'Overall accuracy: {overall_accuracy}')



Overall accuracy: 0.9704861044883728
