<a href="https://colab.research.google.com/github/ganeshagrahari/Pytorch-Framework/blob/main/tensor_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#for checking the current version of torch
import torch
print(torch.__version__)

2.5.1+cu124


In [3]:
#for checking the if we habe GPU or not !
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU :{torch.cuda.get_device_name(0)}")#for print the name of available GPU!
else:
  print("GPU is not available, using CPU!")

GPU is available!
Using GPU :Tesla T4


## Creating a Tensor


In [4]:
#Using empty:-
a=torch.empty(2,3) #two dimentional
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
#check type
type(a)

torch.Tensor

In [6]:
#using zeros :-
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
#using ones :-
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
#using rand:-
torch.rand(2,3)

tensor([[0.4629, 0.5375, 0.0483],
        [0.1913, 0.2201, 0.3680]])

In [9]:
#using seed :-
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
#using tensor:-
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
#other ways

#arange
print("using arange -> ",torch.arange(0,10,2))

#using linspace
print("Using linspace ->", torch.linspace(0,10,10))

#using eyes
print("Using eyes -> ",torch.eye(5)) #identity matrix

#using full
print("Using full -> ",torch.full((3,3),5))

using arange ->  tensor([0, 2, 4, 6, 8])
Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eyes ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Shaping tensor

In [13]:
x = torch.tensor([[1,2,3],[4,5,7]])
x

tensor([[1, 2, 3],
        [4, 5, 7]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[    135473521835408,     135473521835408,                   0],
        [                  0,                   0, 7310593858020254331]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Type

In [18]:
#Find data type
x.dtype

torch.int64

In [19]:
# assign datatype
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [20]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [21]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 7.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical Operations

### 1. Scalar operation

In [22]:
x =torch.rand(2,3)
x

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [23]:
#Addtion
x+2

tensor([[2.7118, 2.7876, 2.4183],
        [2.9014, 2.9969, 2.7565]])

In [24]:
#subtraction
x-2

tensor([[-1.2882, -1.2124, -1.5817],
        [-1.0986, -1.0031, -1.2435]])

In [25]:
#multiplication
x*2

tensor([[1.4235, 1.5752, 0.8366],
        [1.8028, 1.9938, 1.5130]])

In [26]:
#divition
x/2

tensor([[0.3559, 0.3938, 0.2092],
        [0.4507, 0.4984, 0.3783]])

In [27]:
#int divition
(x*100)//3

tensor([[23., 26., 13.],
        [30., 33., 25.]])

In [28]:
#mod
((x*100)//3)%2

tensor([[1., 0., 1.],
        [0., 1., 1.]])

In [29]:
x**2

tensor([[0.5066, 0.6203, 0.1750],
        [0.8125, 0.9938, 0.5723]])

### 2. Element wise operation

In [30]:
a = torch.rand(2,3)
b =torch.rand(2,3)

In [31]:
print(a)
print(b)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])


In [32]:
#add
a+b

tensor([[0.6679, 1.2502, 0.9229],
        [1.3130, 0.7983, 1.6774]])

In [33]:
#sub
a-b

tensor([[-0.2201, -0.6455, -0.5661],
        [ 0.3346,  0.3132,  0.2767]])

In [34]:
#mul
a*b

tensor([[0.0994, 0.2866, 0.1328],
        [0.4030, 0.1348, 0.6842]])

In [35]:
#div
a/b

tensor([[0.5042, 0.3190, 0.2397],
        [1.6841, 2.2912, 1.3951]])

In [36]:
#power
a**b

tensor([[0.5145, 0.3218, 0.2771],
        [0.9096, 0.8672, 0.9839]])

In [37]:
#mod
a%b

tensor([[0.2239, 0.3023, 0.1784],
        [0.3346, 0.0706, 0.2767]])

In [38]:
c =torch.tensor([1,-2,3,-4])

In [39]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [40]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [41]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [42]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [43]:
#ceil
torch.ceil(d)


tensor([2., 3., 4., 5.])

In [44]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [45]:
#clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [46]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[7., 0., 0.],
        [9., 5., 7.]])

In [47]:
#sum of all element
torch.sum(e)

tensor(28.)

In [48]:
# sum along with colums
torch.sum(e,dim=0)

tensor([16.,  5.,  7.])

In [49]:
# sum along with rows
torch.sum(e,dim=1)

tensor([ 7., 21.])

In [50]:
#mean
torch.mean(e)

tensor(4.6667)

In [51]:
#median
torch.median(e)

tensor(5.)

In [52]:
#max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [53]:
#product
torch.prod(e)

tensor(0.)

In [54]:
#stdandard
torch.std(e)

tensor(3.8297)

In [55]:
#varience
torch.var(e)

tensor(14.6667)

In [56]:
#argmax
torch.argmax(e)

tensor(3)

In [57]:
#argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [58]:
f = torch.randint(size=(2,3),low =0, high=10)
g = torch.randint(size=(3,2),low=0,high=10)

In [59]:
print(f)
print(g)

tensor([[3, 9, 4],
        [0, 5, 7]])
tensor([[5, 9],
        [9, 7],
        [5, 9]])


In [60]:
#matrix multiplication
torch.matmul(f,g)

tensor([[116, 126],
        [ 80,  98]])

In [61]:
vector1 =torch.tensor([1,2])
vector2= torch.tensor([3,4])


In [62]:
#dot product
torch.dot(vector1,vector2)

tensor(11)

In [63]:
#transpose
print(f)
torch.transpose(f,0,1)

tensor([[3, 9, 4],
        [0, 5, 7]])


tensor([[3, 0],
        [9, 5],
        [4, 7]])

In [64]:
h =torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[8., 9., 7.],
        [9., 2., 6.],
        [7., 7., 8.]])

In [65]:
#determinant
torch.det(h)

tensor(-135.0000)

In [66]:
#inverse
torch.inverse(h)

tensor([[ 0.1926,  0.1704, -0.2963],
        [ 0.2222, -0.1111, -0.1111],
        [-0.3630, -0.0519,  0.4815]])

### 5. coamprison operation

In [67]:
i = torch.randint(size=(2,3),low=0,high=10)
j =torch.randint(size=(2,3),low=0,high=10)

In [68]:
print(i)
print(j)

tensor([[3, 6, 1],
        [5, 5, 0]])
tensor([[4, 3, 8],
        [8, 3, 3]])


In [69]:
#greater than
i > j

tensor([[False,  True, False],
        [False,  True, False]])

In [70]:
#equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [71]:
#greater than equal to
i >=j

tensor([[False,  True, False],
        [False,  True, False]])

In [72]:
#less than equal to
i <= j

tensor([[ True, False,  True],
        [ True, False,  True]])

### 6. Special functions

In [73]:
k = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[5., 0., 6.],
        [4., 0., 8.]])

In [74]:
#log
torch.log(k)

tensor([[1.6094,   -inf, 1.7918],
        [1.3863,   -inf, 2.0794]])

In [75]:
#exp
torch.exp(k)

tensor([[1.4841e+02, 1.0000e+00, 4.0343e+02],
        [5.4598e+01, 1.0000e+00, 2.9810e+03]])

In [76]:
#sqrt
torch.sqrt(k)

tensor([[2.2361, 0.0000, 2.4495],
        [2.0000, 0.0000, 2.8284]])

In [77]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9933, 0.5000, 0.9975],
        [0.9820, 0.5000, 0.9997]])

In [78]:
#softmax
torch.softmax(k ,dim=0)

tensor([[0.7311, 0.5000, 0.1192],
        [0.2689, 0.5000, 0.8808]])

In [79]:
#relu
torch.relu(k)

tensor([[5., 0., 6.],
        [4., 0., 8.]])

## Inplace Operations

In [80]:
m = torch.rand(2,3)
n = torch.rand(2,3)

In [81]:
print(m)
print(n)

tensor([[0.0453, 0.9798, 0.5548],
        [0.6868, 0.4920, 0.0748]])
tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])


In [82]:
m+n

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [83]:
# if we wana stroe m+n in m
m.add_(n)

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [84]:
m

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [85]:
n

tensor([[0.9605, 0.3271, 0.0103],
        [0.9516, 0.2855, 0.2324]])

In [86]:
torch.relu(m)

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [87]:
m.relu_()

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

In [88]:
m

tensor([[1.0058, 1.3069, 0.5650],
        [1.6384, 0.7776, 0.3072]])

## Coping a Tensor

In [89]:
a = torch.rand(2,3)
a

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [90]:
b = a

In [91]:
b

tensor([[0.9141, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [92]:
a[0][0]=0

In [93]:
a

tensor([[0.0000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [94]:
b


tensor([[0.0000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [95]:
id(a)

135469252978800

In [96]:
id(b)

135469252978800

In [97]:
b=a.clone()

In [98]:
a

tensor([[0.0000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [99]:
b

tensor([[0.0000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

In [100]:
a[0][0]=10

In [101]:
a

tensor([[10.0000,  0.7668,  0.1659],
        [ 0.4393,  0.2243,  0.8935]])

In [102]:
b

tensor([[0.0000, 0.7668, 0.1659],
        [0.4393, 0.2243, 0.8935]])

## Tensor Operations on GPU

In [103]:
torch.cuda.is_available()

True

In [104]:
device = torch.device('cuda')

In [105]:
# creating a new tensor on GPU
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [106]:
#moving an exiting tensor to GPU
a = torch.rand(2,3)
a

tensor([[0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])

In [107]:
b =a.to(device=device)

In [108]:
b+5

tensor([[5.0497, 5.1780, 5.3011],
        [5.1893, 5.9186, 5.2131]], device='cuda:0')

In [109]:
import time
#define the size of the matrices
size=10000 #large size for performance camparison

#create random matrices on CPU
matrix_cpu1=torch.randn(size,size)
matrix_cpu2=torch.randn(size,size)

#measure the the on cpu
start_time=time.time()
result_cpu=torch.matmul(matrix_cpu1,matrix_cpu2) #Matrix multiplication CPU
cpu_time=time.time()-start_time

print(f"time on cpu :{cpu_time:4f} seconds ")

#move matrices to GPU
matrix_gpu1=matrix_cpu1.to('cuda')
matrix_gpu2=matrix_cpu2.to('cuda')

#measure the time on gpu
start_time =time.time()
result_gpu=torch.matmul(matrix_gpu1,matrix_gpu2) # matrix multiplication on GPU
torch.cuda.synchronize()#ensure all GPU operation on GPU
gpu_time=time.time()-start_time


print(f"TIme on GPU :{gpu_time:4f} seconds")

#Compare results
print("\nSpeed (cpu time/ gpu time ): ",cpu_time / gpu_time)




time on cpu :15.735117 seconds 
TIme on GPU :0.680646 seconds

Speed (cpu time/ gpu time ):  23.117910409596064


## Reshaping Tensors

In [110]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [111]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [112]:
#flaten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [113]:
b =torch.rand(2,3,4)
b

tensor([[[0.9514, 0.0141, 0.8903, 0.1649],
         [0.3162, 0.1331, 0.6763, 0.4254],
         [0.2375, 0.5430, 0.1174, 0.6532]],

        [[0.5115, 0.3094, 0.7907, 0.7351],
         [0.2693, 0.8009, 0.5839, 0.0061],
         [0.4671, 0.8243, 0.2861, 0.7459]]])

In [116]:
#permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [118]:
#unsqueez
#image size
c =torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [119]:
#squeez
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## Numpy and Pytorch

In [120]:
import numpy as np

In [121]:
a =torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [122]:
b=a.numpy()

In [123]:
b

array([1, 2, 3])

In [124]:
type(b)

numpy.ndarray

In [125]:
c =np.array([1,2,3])
c

array([1, 2, 3])

In [126]:
d = torch.from_numpy(c)
d

tensor([1, 2, 3])