In [1]:
#for checking the current version of torch
import torch
print(torch.__version__)

2.5.1+cu124


In [2]:
#for checking the if we habe GPU or not !
if torch.cuda.is_available():
  print("GPU is available!")
  print(f"Using GPU :{torch.cuda.get_device_name(0)}")#for print the name of available GPU!
else:
  print("GPU is not available, using CPU!")

GPU is available!
Using GPU :Tesla T4


## Creating a Tensor


In [3]:
#Using empty:-
a=torch.empty(2,3) #two dimentional
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [4]:
#check type
type(a)

torch.Tensor

In [5]:
#using zeros :-
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
#using ones :-
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
#using rand:-
torch.rand(2,3)

tensor([[0.7348, 0.4199, 0.5544],
        [0.9291, 0.9878, 0.3165]])

In [8]:
#using seed :-
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [9]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
#using tensor:-
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
#other ways

#arange
print("using arange -> ",torch.arange(0,10,2))

#using linspace
print("Using linspace ->", torch.linspace(0,10,10))

#using eyes
print("Using eyes -> ",torch.eye(5)) #identity matrix

#using full
print("Using full -> ",torch.full((3,3),5))

using arange ->  tensor([0, 2, 4, 6, 8])
Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
Using eyes ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Shaping tensor

In [12]:
x = torch.tensor([[1,2,3],[4,5,7]])
x

tensor([[1, 2, 3],
        [4, 5, 7]])

In [13]:
x.shape

torch.Size([2, 3])

In [14]:
torch.empty_like(x)

tensor([[3616445622929465956, 6066684243230076213, 4121139116991199025],
        [6500164546373629230, 7309453675965983778, 8315168162784306286]])

In [15]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [16]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

## Tensor Data Type

In [17]:
#Find data type
x.dtype

torch.int64

In [18]:
# assign datatype
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [19]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [20]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 7.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical Operations

### 1. Scalar operation

In [21]:
x =torch.rand(2,3)
x

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

In [22]:
#Addtion
x+2

tensor([[2.7118, 2.7876, 2.4183],
        [2.9014, 2.9969, 2.7565]])

In [23]:
#subtraction
x-2

tensor([[-1.2882, -1.2124, -1.5817],
        [-1.0986, -1.0031, -1.2435]])

In [24]:
#multiplication
x*2

tensor([[1.4235, 1.5752, 0.8366],
        [1.8028, 1.9938, 1.5130]])

In [25]:
#divition
x/2

tensor([[0.3559, 0.3938, 0.2092],
        [0.4507, 0.4984, 0.3783]])

In [26]:
#int divition
(x*100)//3

tensor([[23., 26., 13.],
        [30., 33., 25.]])

In [27]:
#mod
((x*100)//3)%2

tensor([[1., 0., 1.],
        [0., 1., 1.]])

In [28]:
x**2

tensor([[0.5066, 0.6203, 0.1750],
        [0.8125, 0.9938, 0.5723]])

### 2. Element wise operation

In [29]:
a = torch.rand(2,3)
b =torch.rand(2,3)

In [30]:
print(a)
print(b)

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])
tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])


In [31]:
#add
a+b

tensor([[0.6679, 1.2502, 0.9229],
        [1.3130, 0.7983, 1.6774]])

In [32]:
#sub
a-b

tensor([[-0.2201, -0.6455, -0.5661],
        [ 0.3346,  0.3132,  0.2767]])

In [33]:
#mul
a*b

tensor([[0.0994, 0.2866, 0.1328],
        [0.4030, 0.1348, 0.6842]])

In [34]:
#div
a/b

tensor([[0.5042, 0.3190, 0.2397],
        [1.6841, 2.2912, 1.3951]])

In [35]:
#power
a**b

tensor([[0.5145, 0.3218, 0.2771],
        [0.9096, 0.8672, 0.9839]])

In [36]:
#mod
a%b

tensor([[0.2239, 0.3023, 0.1784],
        [0.3346, 0.0706, 0.2767]])

In [37]:
c =torch.tensor([1,-2,3,-4])

In [38]:
#abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [39]:
#negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [40]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [41]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [42]:
#ceil
torch.ceil(d)


tensor([2., 3., 4., 5.])

In [43]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [44]:
#clamp
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [45]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[7., 0., 0.],
        [9., 5., 7.]])

In [46]:
#sum of all element
torch.sum(e)

tensor(28.)

In [47]:
# sum along with colums
torch.sum(e,dim=0)

tensor([16.,  5.,  7.])

In [48]:
# sum along with rows
torch.sum(e,dim=1)

tensor([ 7., 21.])

In [49]:
#mean
torch.mean(e)

tensor(4.6667)

In [50]:
#median
torch.median(e)

tensor(5.)

In [51]:
#max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [52]:
#product
torch.prod(e)

tensor(0.)

In [53]:
#stdandard
torch.std(e)

tensor(3.8297)

In [54]:
#varience
torch.var(e)

tensor(14.6667)

In [55]:
#argmax
torch.argmax(e)

tensor(3)

In [56]:
#argmin
torch.argmin(e)

tensor(1)

### 4. Matrix operations

In [61]:
f = torch.randint(size=(2,3),low =0, high=10)
g = torch.randint(size=(3,2),low=0,high=10)

In [62]:
print(f)
print(g)

tensor([[8, 9, 7],
        [9, 2, 6]])
tensor([[7, 7],
        [8, 3],
        [6, 1]])


In [63]:
#matrix multiplication
torch.matmul(f,g)

tensor([[170,  90],
        [115,  75]])

In [64]:
vector1 =torch.tensor([1,2])
vector2= torch.tensor([3,4])


In [65]:
#dot product
torch.dot(vector1,vector2)

tensor(11)

In [69]:
#transpose
print(f)
torch.transpose(f,0,1)

tensor([[8, 9, 7],
        [9, 2, 6]])


tensor([[8, 9],
        [9, 2],
        [7, 6]])

In [75]:
h =torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[3., 8., 5.],
        [6., 2., 9.],
        [5., 0., 4.]])

In [76]:
#determinant
torch.det(h)

tensor(142.)

In [77]:
#inverse
torch.inverse(h)

tensor([[ 0.0563, -0.2254,  0.4366],
        [ 0.1479, -0.0915,  0.0211],
        [-0.0704,  0.2817, -0.2958]])

### 5. coamprison operation

In [78]:
i = torch.randint(size=(2,3),low=0,high=10)
j =torch.randint(size=(2,3),low=0,high=10)

In [79]:
print(i)
print(j)

tensor([[2, 7, 1],
        [1, 5, 4]])
tensor([[4, 1, 1],
        [2, 4, 7]])


In [80]:
#greater than
i > j

tensor([[False,  True, False],
        [False,  True, False]])

In [81]:
#equal to
i == j

tensor([[False, False,  True],
        [False, False, False]])

In [82]:
#greater than equal to
i >=j

tensor([[False,  True,  True],
        [False,  True, False]])

In [83]:
#less than equal to
i <= j

tensor([[ True, False,  True],
        [ True, False,  True]])

### 6. Special functions

In [90]:
k = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[6., 9., 2.],
        [3., 1., 0.]])

In [85]:
#log
torch.log(k)

tensor([[0.6931, 1.6094, 1.7918],
        [0.0000, 1.3863, 1.6094]])

In [86]:
#exp
torch.exp(k)

tensor([[  7.3891, 148.4132, 403.4288],
        [  2.7183,  54.5981, 148.4132]])

In [87]:
#sqrt
torch.sqrt(k)

tensor([[1.4142, 2.2361, 2.4495],
        [1.0000, 2.0000, 2.2361]])

In [88]:
# sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.9933, 0.9975],
        [0.7311, 0.9820, 0.9933]])

In [91]:
#softmax
torch.softmax(k ,dim=0)

tensor([[9.5257e-01, 9.9966e-01, 8.8080e-01],
        [4.7426e-02, 3.3535e-04, 1.1920e-01]])

In [92]:
#relu
torch.relu(k)

tensor([[6., 9., 2.],
        [3., 1., 0.]])