<a href="https://colab.research.google.com/github/ganeshagrahari/Pytorch-Framework/blob/main/Training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Plan of attack:-**
## 1. We will build a simple neural network
## 2. Train it on world dataset
## 3. Will mimic the Pytorch workflow
## 4. End result is not important


# Code flow:-
## 1. Load the dataset
## 2. Basic preprocessing
## 3. Training process :- a) Creating the model.  b) Forward pass  c)Loss calculation  d)Backprop e)Parameters update
## 4. Model evaluation

In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df =pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [4]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [5]:
df.shape

(569, 33)

In [8]:
df.drop(columns={'id','Unnamed: 32'},inplace=True)

In [10]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

## Train Test Split

In [11]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

## Scaling

In [13]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
X_train

array([[ 1.53740179,  1.76471886,  1.56412694, ...,  0.99958606,
         1.24369936,  1.57686441],
       [-0.30490461, -1.29314489, -0.38315461, ..., -1.22287437,
        -1.28407199, -0.99068126],
       [-0.37895229, -0.41670255, -0.36850368, ..., -0.48339948,
        -1.47627952, -0.72950941],
       ...,
       [-0.65440968,  0.57111092, -0.63652959, ..., -0.41292895,
        -0.9642645 ,  0.87120347],
       [ 0.1364196 ,  2.02377779,  0.22098098, ...,  0.88627441,
         2.12559275,  2.780574  ],
       [ 0.10680052, -0.96871595,  0.10204987, ...,  0.7108742 ,
        -0.3408014 , -0.38164839]])

In [15]:
y_train

33     M
309    B
397    B
55     B
357    B
      ..
441    M
242    B
450    B
15     M
148    B
Name: diagnosis, Length: 455, dtype: object

## Label encoder

In [16]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [17]:
y_train

array([1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,

In [18]:
y_test

array([1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0])

## Numpy array to Pytorch tensors

In [19]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [20]:
X_train_tensor.shape

torch.Size([455, 30])

In [21]:
y_train_tensor.shape

torch.Size([455])

# Defining the model

In [35]:
class MysimpleNN():
  def __init__(self,X):
    self.weights = torch.rand(X.shape[1],1, dtype =torch.float64, requires_grad=True)
    self.bias = torch.zeros(1,dtype= torch.float64,requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X,self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

## Important parameters

In [36]:
learning_rate = 0.1
epochs = 1

## Training Pipeline

In [37]:
# Create model
model = MysimpleNN(X_train_tensor)
model.weights

## defining a loop:---
for epoch in range(epochs):


    #Forward pass
    y_pred = model.forward(X_train_tensor)
    print(y_pred)

    #Loss calculate

    #backward pass

    #parameters update


tensor([[1.0000e+00],
        [1.0294e-06],
        [2.4725e-03],
        [5.5824e-04],
        [1.5379e-04],
        [2.2898e-02],
        [3.3350e-04],
        [1.3564e-05],
        [9.9934e-01],
        [1.9612e-02],
        [1.0000e+00],
        [9.9902e-01],
        [9.9413e-01],
        [1.0380e-01],
        [1.1663e-02],
        [1.0000e+00],
        [9.1403e-06],
        [6.2067e-05],
        [2.0828e-01],
        [2.6720e-04],
        [9.1847e-01],
        [4.6594e-04],
        [3.7889e-06],
        [9.5961e-03],
        [2.2968e-03],
        [9.7344e-06],
        [8.4381e-04],
        [3.0786e-01],
        [3.6257e-01],
        [6.7496e-06],
        [2.2556e-04],
        [9.9994e-01],
        [9.6487e-01],
        [6.8659e-05],
        [9.9995e-01],
        [1.6156e-05],
        [1.0000e+00],
        [6.0328e-01],
        [1.0000e+00],
        [1.7031e-05],
        [2.7646e-07],
        [5.7094e-04],
        [3.0801e-05],
        [1.1435e-01],
        [3.9187e-02],
        [9

In [32]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)